name: Allure Report CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run tests with Allure
        run: mvn clean test -Dallure.results.directory=target/allure-results

      - name: Install Allure CLI
        run: |
          wget -q https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -xzf allure-2.27.0.tgz
          sudo mv allure-2.27.0 /opt/allure
          echo '/opt/allure/bin' | sudo tee -a /etc/environment
          echo "ALLURE_HOME=/opt/allure" | sudo tee -a /etc/environment

      - name: Generate Allure Report
        run: |
          export PATH="$PATH:/opt/allure/bin"
          allure generate target/allure-results --clean -o allure-report
          echo "Report generated at: $(pwd)/allure-report"

      - name: List report contents (debug)
        run: |
          ls -la allure-report/
          echo "HTML files found: $(find allure-report -name "*.html" | wc -l)"

      - name: Upload Allure report artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
          retention-days: 1

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report
          force_orphan: true