name: SauceDemo CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run tests
        run: mvn clean test

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y allure

      - name: Generate Allure report
        run: |
          allure generate target/allure-results -o allure-report --clean
          
          # Проверяем что отчет создан
          if [ ! -f "allure-report/index.html" ]; then
            echo "ERROR: Report generation failed"
            echo "Contents of allure-results:"
            find target/allure-results -type f | head -10
            exit 1
          fi
          echo "Report generated successfully"

      - name: Verify report structure
        run: |
          echo "=== Report structure ==="
          ls -la allure-report/
          echo "=== index.html exists ==="
          test -f allure-report/index.html && echo "✓ index.html found" || echo "✗ index.html missing"
          echo "=== Static files ==="
          find allure-report/ -name "*.js" -o -name "*.css" | head -5

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report