name: SauceDemo CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Create config.properties
        run: |
          mkdir -p src/test/resources
          echo "username=standard_user" > src/test/resources/config.properties
          echo "password=secret_sauce" >> src/test/resources/config.properties
          echo "base.url=https://www.saucedemo.com" >> src/test/resources/config.properties

      - name: Run tests
        run: mvn clean test -Dmaven.test.failure.ignore=true

      - name: Find Allure report
        run: |
          echo "=== Searching for report files ==="
          echo "Contents of target/:"
          ls -la target/
          
          echo "=== Looking for index.html ==="
          find target/ -name "index.html" -type f 2>/dev/null | head -5 || echo "No index.html found"
          
          echo "=== Looking for allure directories ==="
          find target/ -name "*allure*" -type d 2>/dev/null | head -5 || echo "No allure directories found"
          
          echo "=== Looking for site directories ==="
          find target/ -name "*site*" -type d 2>/dev/null | head -5 || echo "No site directories found"

      - name: Generate report with Maven
        run: mvn allure:report
        if: always()

      - name: Check Maven report location
        run: |
          echo "=== After mvn allure:report ==="
          echo "Contents of target/site/:"
          ls -la target/site/ 2>/dev/null || echo "No target/site directory"
          
          echo "Looking for index.html:"
          find target/ -name "index.html" -type f 2>/dev/null | head -3 || echo "No index.html found"

      - name: Create report manually if missing
        run: |
          if [ ! -f "target/site/allure-maven-plugin/index.html" ]; then
            echo "Creating manual report..."
            mkdir -p target/site/allure-maven-plugin
            cat > target/site/allure-maven-plugin/index.html << 'EOF'
            <!DOCTYPE html>
            <html>
            <head>
                <title>Allure Test Report</title>
            </head>
            <body>
                <h1>Test Execution Report</h1>
                <p>Generated: $(date)</p>
                <p>Check workflow logs for test results</p>
            </body>
            </html>
            EOF
          fi
        if: always()

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: target/site/allure-maven-plugin
        if: always()