name: SauceDemo CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Create config.properties
        run: |
          mkdir -p src/test/resources
          cat > src/test/resources/config.properties << EOF
          username=standard_user
          password=secret_sauce
          base.url=https://www.saucedemo.com
          EOF

      - name: Run tests with Allure
        run: |
          # Запускаем тесты с явным указанием агента Allure
          mvn clean test -Dmaven.test.failure.ignore=true \
            -DargLine="-javaagent:./aspectjweaver-1.9.20.jar"

      - name: Download AspectJ weaver
        run: |
          # Скачиваем aspectjweaver явно
          wget -O aspectjweaver-1.9.20.jar \
            https://repo1.maven.org/maven2/org/aspectj/aspectjweaver/1.9.20/aspectjweaver-1.9.20.jar

      - name: Verify Allure results
        run: |
          echo "=== Allure results ==="
          ls -la target/allure-results/ || echo "No allure-results directory"
          find target/allure-results/ -name "*.json" | head -5 || echo "No JSON files found"
          echo "Total files: $(find target/allure-results/ -type f 2>/dev/null | wc -l || echo 0)"

      - name: Generate Allure report
        run: |
          # Генерируем отчет через Maven
          mvn allure:report
          echo "=== Report directory ==="
          ls -la target/site/allure-maven-plugin/ || echo "No report directory"

      - name: Create index.html if missing
        run: |
          if [ ! -f "target/site/allure-maven-plugin/index.html" ]; then
            echo "Creating fallback index.html..."
            mkdir -p target/site/allure-maven-plugin
            cat > target/site/allure-maven-plugin/index.html << EOF
            <!DOCTYPE html>
            <html>
            <head>
                <title>Allure Report</title>
            </head>
            <body>
                <h1>Allure Test Report</h1>
                <p>Generated: $(date)</p>
                <p>Tests were executed. Check workflow logs for details.</p>
            </body>
            </html>
            EOF
          fi
        if: always()

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: target/site/allure-maven-plugin
        if: always()