name: SauceDemo CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Install Allure CLI
        run: |
          # Устанавливаем Allure CLI
          sudo apt-get update
          wget https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.tgz
          tar -zxvf allure-2.24.0.tgz
          sudo cp -r allure-2.24.0/* /usr/local/bin/
          allure --version

      - name: Create config.properties
        run: |
          mkdir -p src/test/resources
          echo "username=standard_user" > src/test/resources/config.properties
          echo "password=secret_sauce" >> src/test/resources/config.properties
          echo "base.url=https://www.saucedemo.com" >> src/test/resources/config.properties

      - name: Run tests with Allure
        run: mvn clean test -Dmaven.test.failure.ignore=true

      - name: Generate Allure report
        run: |
          # Генерируем полноценный Allure отчет
          allure generate target/allure-results -o allure-report --clean
          echo "Allure report generated"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report