name: SauceDemo CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      USER: ${{secrets.SD_USER}}
      PASSWORD: ${{secrets.SD_PASSWORD}}

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run tests
      run: mvn clean test -Duser=$USER -Dpassword=$PASSWORD

    - name: List Allure results
      run: |
        echo "Allure results directory:"
        ls -la target/allure-results/ || true
        echo "Number of files:"
        find target/allure-results/ -name "*.json" -o -name "*.txt" | wc -l || true
      if: always()

    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
          allure_results: target/allure-results
          allure_report: allure-report
          keep_history: true

    - name: Deploy report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report