name: SauceDemo CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Create config.properties
        run: |
          mkdir -p src/test/resources
          cat > src/test/resources/config.properties << EOF
          username=standard_user
          password=secret_sauce
          base.url=https://www.saucedemo.com
          EOF

      - name: Run tests with Allure (ignore failures)
        run: mvn clean test -Dmaven.test.failure.ignore=true

      - name: Generate Allure report with Maven
        run: mvn allure:report
        if: always()

      - name: Verify report generation
        run: |
          echo "=== Checking Maven report ==="
          if [ -d "target/site/allure-maven-plugin" ]; then
            echo "✓ Allure report generated"
            echo "Files found: $(find target/site/allure-maven-plugin -type f | wc -l)"
            if [ -f "target/site/allure-maven-plugin/index.html" ]; then
              echo "✓ index.html exists"
            else
              echo "✗ index.html missing"
            fi
          else
            echo "✗ Allure report not generated"
          fi
        if: always()

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: target/site/allure-maven-plugin
        if: always()