name: SauceDemo CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Create config.properties
        run: |
          mkdir -p src/test/resources
          echo "username=standard_user" > src/test/resources/config.properties
          echo "password=secret_sauce" >> src/test/resources/config.properties
          echo "base.url=https://www.saucedemo.com" >> src/test/resources/config.properties

      - name: Run tests
        run: mvn clean test -Dmaven.test.failure.ignore=true

      - name: Generate report
        run: |
          mkdir -p allure-report
          echo '<!DOCTYPE html>' > allure-report/index.html
          echo '<html>' >> allure-report/index.html
          echo '<head><title>Test Report</title></head>' >> allure-report/index.html
          echo '<body>' >> allure-report/index.html
          echo '<h1>Test Report</h1>' >> allure-report/index.html
          echo '<p>Tests completed</p>' >> allure-report/index.html
          echo '</body>' >> allure-report/index.html
          echo '</html>' >> allure-report/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report